name: Docker Build

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    docker:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build Docker Image
              run: docker build -t my-go-app .