name: Go Build & Test

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.22'
            - name: Build Go projects
              run: go build ./...
            - name: Run Go tests
              run: go test ./...